name: Build and Commit

on:
  push:
    branches:
      - main  # Adjust this to your default branch

permissions:
  contents: write  # Ensure the token has write permissions for contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies with frozen lockfile
      run: yarn install --frozen-lockfile

    - name: Build the project
      run: |
        mkdir -p dist
        yarn esbuild node_modules/postcss-cli/index.js --bundle --platform=node --outdir=dist
        yarn esbuild postcss.config.js --bundle --platform=node --outdir=dist

    - name: Commit built files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -f dist
        git diff-index --quiet HEAD -- || git commit -m 'Add built files'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
